# Generated by Django 4.2.5 on 2023-09-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data',
            field=models.DateField(null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
