<<<<<<< HEAD
# Generated by Django 4.2.5 on 2023-09-26 17:01
=======
# Generated by Django 4.2.5 on 2023-09-21 12:15
>>>>>>> 753be2c7875d7f27c99378cb516f17bfc4a56231

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data',
<<<<<<< HEAD
            field=models.DateField(null=b'I01\n'),
            preserve_default=b'I01\n',
=======
            field=models.DateField(null=True),
>>>>>>> 753be2c7875d7f27c99378cb516f17bfc4a56231
        ),
    ]
