# Generated by Django 4.2.5 on 2023-09-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_stand_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='valor',
            field=models.FloatField(),
        ),
    ]
