# Generated by Django 4.2.5 on 2023-09-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_reserva_stand'),
        ('core', '0004_alter_stand_valor'),
    ]

    operations = [
    ]
