# Generated by Django 4.2.5 on 2023-09-28 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_reserva_data_alter_reserva_stand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='stand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stand'),
        ),
    ]
